#!/usr/bin/env bash
# =====================================================================
# Tax-ETS — MOF Customer Installer
# ---------------------------------------------------------------------
# Target: MOF Laos server behind Fortigate VPN, local IP only.
# No internet access is assumed, so we use pre-loaded Docker images.
#
# What this script does:
#   1. Verifies Docker is installed.
#   2. Loads the tax-ets image from a .tar file (if not already loaded).
#   3. Asks the user a few questions (DB host, port, password).
#   4. Writes a .env file with the answers.
#   5. Brings up the `web` container, leaving DB on the customer's network.
#
# Run it ONCE on the MOF server:
#   sudo bash install.sh
# =====================================================================

set -euo pipefail

# ---- Pretty output ----
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
say()    { echo -e "${BLUE}==>${NC} $*"; }
ok()     { echo -e "${GREEN}✓${NC} $*"; }
warn()   { echo -e "${YELLOW}!${NC} $*"; }
err()    { echo -e "${RED}✗${NC} $*" >&2; }
header() { echo -e "\n${BOLD}==== $* ====${NC}"; }

# ---- 1. Sanity checks ----
header "Step 1/5: Verifying Docker installation"

if ! command -v docker >/dev/null 2>&1; then
    err "Docker is not installed. Please install Docker Engine first."
    err "On Ubuntu: curl -fsSL https://get.docker.com | sh"
    exit 1
fi
ok "Docker found: $(docker --version)"

if ! docker compose version >/dev/null 2>&1; then
    err "Docker Compose plugin is not installed."
    err "On Ubuntu: sudo apt install docker-compose-plugin"
    exit 1
fi
ok "Docker Compose found: $(docker compose version --short)"

# ---- 2. Load pre-built image from USB (if not already loaded) ----
header "Step 2/5: Loading Docker image"

if docker image inspect tax-ets:latest >/dev/null 2>&1; then
    ok "Image tax-ets:latest already loaded (skipping import)"
else
    say "Looking for tax-ets-image.tar in the current directory..."
    if [[ ! -f tax-ets-image.tar ]]; then
        err "tax-ets-image.tar not found in $(pwd)"
        err "Copy the image from the USB stick to this directory first."
        exit 1
    fi
    say "Loading image (this can take 1-2 minutes)..."
    docker load -i tax-ets-image.tar
    ok "Image loaded successfully"
fi

# ---- 3. Ask the user questions ----
header "Step 3/5: Database connection settings"

read -rp "DB host (IP or hostname) [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-localhost}

read -rp "DB port [3306]: " DB_PORT
DB_PORT=${DB_PORT:-3306}

read -rp "DB name [tax_ets]: " DB_NAME
DB_NAME=${DB_NAME:-tax_ets}

read -rp "DB user [tax_ets_user]: " DB_USER
DB_USER=${DB_USER:-tax_ets_user}

read -rsp "DB password: " DB_PASS
echo
if [[ -z "$DB_PASS" ]]; then
    err "DB password cannot be empty."
    exit 1
fi

read -rp "Public base URL (e.g. /tax-ets, leave empty if app is at web root) []: " BASE_URL
BASE_URL=${BASE_URL:-}

# ---- 4. Write .env file ----
header "Step 4/5: Writing .env file"

cat > .env <<EOF
# Generated by install.sh on $(date)
# MOF Tax-ETS deployment
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
BASE_URL=${BASE_URL}
TZ=Asia/Vientiane
EOF

chmod 600 .env   # protect the password file
ok ".env written (mode 600 — only root can read)"

# ---- 5. Start the app ----
header "Step 5/5: Starting Tax-ETS container"

say "Pulling up the web container (DB is on the customer's network)..."
docker compose up -d web

# ---- 6. Verify ----
say "Waiting 10 seconds for the container to start..."
sleep 10

if docker ps | grep -q tax-ets-web; then
    ok "Container is running!"
else
    err "Container failed to start. Check logs:"
    err "  docker compose logs web"
    exit 1
fi

# ---- 7. Print final info ----
header "Installation complete!"
echo
ok "Tax-ETS is now running."
echo
echo -e "  • Web UI:    ${BOLD}http://<this-server-ip>${BASE_URL}/${NC}"
echo -e "  • Login:     ${BOLD}http://<this-server-ip>${BASE_URL}/login.php${NC}"
echo -e "  • Logs:      ${BOLD}docker compose logs -f web${NC}"
echo -e "  • Stop:      ${BOLD}docker compose down${NC}"
echo -e "  • Restart:   ${BOLD}docker compose restart web${NC}"
echo
warn "Default login: admin@example.com / admin123"
warn "CHANGE THE DEFAULT PASSWORD after the first login!"
echo
echo -e "${BOLD}Files written:${NC}"
echo "  .env              — your config (KEEP SECRET)"
echo "  docker-compose.yml — copied from the bundle"
echo
