-- Salary Tax Schema (comprehensive)
-- Combines the original import_salary_tax_data table with new reference tables
-- for provisions and benchmark rates, following the same pattern as PIT.
--
-- For the complete salary tax setup, run:
--   1. db/salary_tax_schema.sql  (all tables)
--   2. db/seed_salary.sql        (reference data)

-- The comprehensive schema is now at: db/salary_tax_schema.sql
-- Seed data at: db/seed_salary.sql
--
-- This file is kept for backward compatibility.
