USE tax_ets;

-- Truncate existing records to avoid duplicates and ensure a clean seed
TRUNCATE TABLE bm_customs_regime_codes;

-- Insert records from legacy system
INSERT INTO bm_customs_regime_codes (regime_code, description) VALUES
('1000', 'Exportation'),
('1040', 'Exportation after Importation for Consumption'),
('1100', 'Simplified Declaration Exportation'),
('2000', 'Temporary Exportation'),
('3045', 'Re-Exportation of Importation for Exportation'),
('3050', 'Re-Exportation after General Temporary Importation'),
('3051', 'Re-Exportation after Temporary Importation for Special Economic Zone'),
('3052', 'Re-Exportation after Temporary Importation for manufacturing'),
('3054', 'Re-Exportation after Temporary Importation of International Organizations and Embassies'),
('3055', 'Re-Exportation after Temporary Importation through C2000 System'),
('3056', 'Re-Exportation after Temporary Importation of Government’ Investment Projects'),
('3057', 'Re-Exportation after Temporary Importation of Private’ Investment Projects'),
('3071', 'Re-Exportation after Importation under Duty Free Shops Warehousing Regime'),
('3072', 'Re-Exportation after Importation for Duty Free Shops'),
('4000', 'Importation for Consumption'),
('4050', 'Importation for Consumption after General Temporary Importation'),
('4051', 'Importation for Consumption after Temporary Importation for Special Economic Zone'),
('4052', 'Importation for Consumption after Temporary Importation for manufacturing'),
('4054', 'Importation for Consumption after Temporary Importation of International Organizations and Embassies'),
('4055', 'Importation for Consumption after Temporary Importation through C2000 System'),
('4056', 'Importation for Consumption after Temporary Importation of Government’ Investment Projects'),
('4057', 'Importation for Consumption after Temporary Importation of Private’ Investment Projects'),
('4071', 'Importation for Consumption after Importation under Duty Free Warehousing Regime'),
('4072', 'Importation for Consumption after Importation for Duty Free Shops'),
('4081', 'Importation for Consumption after Importation under Guarantee'),
('4085', 'Importation for Consumption after Importation under Guarantee through C2000 System'),
('4400', 'Simplified Declaration for Importation'),
('5000', 'General Temporary Importation'),
('5085', 'General Temporary Importation after Importation under Guarantee through C2000 System'),
('5100', 'Temporary Importation for Special Economic Zone'),
('5281', 'Temporary Importation of factories for manufacturing after Importation under Guarantee'),
('5285', 'Temporary Importation of factories for manufacturing after Importation under Guarantee through C2000 System'),
('5400', 'Temporary Importation of International Organizations and Embassies'),
('5500', 'Temporary Importation through C2000 System'),
('5600', 'Temporary Importation of Government’ Investment Projects'),
('5681', 'Temporary Importation of Government’ Investment Projects after Importation under Guarantee'),
('5685', 'Temporary Importation of Government’ Investment Projects after Importation under Guarantee through C2000 System'),
('5700', 'Temporary Importation of Private’ Investment Projects'),
('5781', 'Temporary Importation of Private’ Investment Projects after Importation under Guarantee'),
('5785', 'Temporary Importation of Private’ Investment Projects after Importation under Guarantee through C2000 System'),
('6020', 'Re-Importation after Temporary Exportation'),
('7100', 'Importation for Duty Free Warehousing');
