USE tax_ets;

-- Truncate existing data to replace with legacy data
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE moic_sub_categories;
TRUNCATE TABLE moic_categories;
SET FOREIGN_KEY_CHECKS = 1;

-- Insert Main Categories
INSERT INTO moic_categories (id, category_name) VALUES
(1, 'Forestry and logging'),
(2, 'Fishing and aquaculture'),
(3, 'Crop and animal production, hunting and related service activities'),
(4, 'Mining of coal and lignite'),
(5, 'Extraction of crude petroleum and natural gas'),
(6, 'Mining of metal ores'),
(7, 'Other mining and quarrying'),
(8, 'Mining support service activities'),
(9, 'Repair and installation of machinery and equipment'),
(10, 'Manufacture of motor vehicles, trailers and semi-trailers'),
(11, 'Manufacture of other transport equipment'),
(12, 'Manufacture of furniture'),
(13, 'Manufacture of jewellery and related articles'),
(14, 'Manufacture of electrical equipment'),
(15, 'Manufacture of machinery and equipment n.e.c.'),
(16, 'Manufacture of fabricated metal products, except machinery and equipment'),
(17, 'Manufacture of computer, electronic and optical products'),
(18, 'Manufacture of basic pharmaceutical products and pharmaceutical preparations'),
(19, 'Manufacture of rubber and plastics products'),
(20, 'Manufacture of other non-metallic mineral products'),
(21, 'Manufacture of basic metals'),
(22, 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials'),
(23, 'Manufacture of paper and paper products'),
(24, 'Printing and reproduction of recorded media'),
(25, 'Manufacture of coke and refined petroleum products'),
(26, 'Manufacture of chemicals and chemical products'),
(27, 'Manufacture of beverages'),
(28, 'Manufacture of tobacco products'),
(29, 'Manufacture of textiles'),
(30, 'Manufacture of wearing apparel'),
(31, 'Manufacturing of leather and related products'),
(32, 'Manufacture of food products'),
(33, 'Electricity, gas, steam and air conditioning supply'),
(34, 'Remediation activities and other waste management services'),
(35, 'Sewerage'),
(36, 'Waste collection, treatment and disposal activities; materials recovery'),
(37, 'Construction of buildings'),
(38, 'Civil engineering'),
(39, 'Specialized construction activities'),
(40, 'Wholesale trade, except of motor vehicles and motorcycles'),
(41, 'Retail trade, except of motor vehicles and motorcycles'),
(42, 'Wholesale and retail trade and repair of motor vehicles and motorcycles'),
(43, 'Land transport and transport via pipelines'),
(44, 'Water transport'),
(45, 'Air transport'),
(46, 'Warehousing and support activities for transportation'),
(47, 'Postal and courier activities'),
(48, 'Accommodation'),
(49, 'Food and beverage service activities'),
(50, 'Motion picture, video and television programme production, sound recording and music publishing activities'),
(51, 'Programming and broadcasting activities'),
(52, 'Telecommunications'),
(53, 'Computer programming, consultancy and related activities'),
(54, 'Information service activities'),
(55, 'Publishing activities'),
(56, 'Financial service activities, except insurance and pension funding'),
(57, 'Insurance, reinsurance and pension funding, except compulsory social security'),
(58, 'Activities auxiliary to financial service and insurance activities'),
(59, 'Real estate activities'),
(60, 'Legal and accounting activities'),
(61, 'Activities of head offices; management consultancy activities'),
(62, 'Architectural and engineering activities; technical testing and analysis'),
(63, 'Scientific research and development'),
(64, 'Advertising and market research'),
(65, 'Other professional, scientific and technical activities'),
(66, 'Veterinary activities'),
(67, 'Employment activities'),
(68, 'Travel agency, tour operator, reservation service and related activities'),
(69, 'Security and investigation activities'),
(70, 'Services to buildings and landscape activities'),
(71, 'Office administrative, office support and other business support activities'),
(72, 'Public administration and defence; compulsory social security'),
(73, 'Education'),
(74, 'Human health activities'),
(75, 'Residential care activities'),
(76, 'Social work activities without accommodation'),
(77, 'Libraries, archives, museums and other cultural activities'),
(78, 'Gambling and betting activities'),
(79, 'Sports activities and amusement and recreation activities'),
(80, 'Creative, arts and entertainment activities'),
(81, 'Activities of membership organizations'),
(82, 'Repair of computers and personal and household goods'),
(83, 'Other personal service activities'),
(84, 'Activities of households as employers of domestic personnel'),
(85, 'Undifferentiated goods- and services-producing activities of private households for own use'),
(86, 'Activities of extraterritorial organizations and bodies'),
(87, 'Water collection, treatment and supply'),
(88, 'Test 1'),
(89, 'Agriculture');

-- Insert Sub Categories
INSERT INTO moic_sub_categories (id, main_category_id, sub_category_name) VALUES
(3, 1, 'Silviculture and other forestry activities'),
(4, 1, 'Logging'),
(5, 1, 'Gathering of non-wood forest products'),
(6, 1, 'Support services to forestry'),
(7, 2, 'Marine fishing'),
(8, 2, 'Freshwater fishing'),
(9, 2, 'Marine aquaculture'),
(10, 2, 'Freshwater aquaculture'),
(11, 3, 'Growing of cereals (except rice), leguminous crops and oil seeds'),
(12, 3, 'Growing of rice'),
(13, 3, 'Growing of vegetables and melons, roots and tubers'),
(14, 3, 'Growing of sugar cane'),
(15, 3, 'Growing of tobacco'),
(16, 3, 'Growing of fibre crops'),
(17, 3, 'Growing of other non-perennial crops'),
(18, 3, 'Growing of grapes'),
(19, 3, 'Growing of tropical and subtropical fruits'),
(20, 3, 'Growing of citrus fruits'),
(21, 3, 'Growing of pome fruits and stone fruits'),
(22, 3, 'Growing of other tree and bush fruits and nuts'),
(23, 3, 'Growing of oleaginous fruits'),
(24, 3, 'Growing of beverage crops'),
(25, 3, 'Growing of spices, aromatic, drug and pharmaceutical crops'),
(26, 3, 'Growing of other perennial crops'),
(27, 3, 'Plant propagation'),
(28, 3, 'Raising of cattle and buffaloes'),
(29, 3, 'Raising of horses and other equines'),
(30, 3, 'Raising of camels and camelids'),
(31, 3, 'Raising of sheep and goats'),
(32, 3, 'Raising of swine/pigs'),
(33, 3, 'Raising of poultry'),
(34, 3, 'Raising of other animals'),
(35, 3, 'Mixed farming'),
(36, 3, 'Support activities for crop production'),
(37, 3, 'Support activities for animal production'),
(38, 3, 'Post-harvest crop activities'),
(39, 3, 'Seed processing for propagation'),
(40, 3, 'Hunting, trapping and related service activities'),
(41, 4, 'Mining of hard coal'),
(42, 4, 'Mining of lignite'),
(43, 5, 'Extraction of crude petroleum'),
(44, 5, 'Extraction of natural gas'),
(45, 6, 'Mining of iron ores'),
(46, 6, 'Mining of uranium and thorium ores'),
(47, 6, 'Mining of other non-ferrous metal ores'),
(48, 7, 'Quarrying of stone, sand and clay'),
(49, 7, 'Mining of chemical and fertilizer minerals'),
(50, 7, 'Extraction of peat'),
(51, 7, 'Extraction of salt'),
(52, 7, 'Other mining and quarrying n.e.c.'),
(53, 8, 'Support activities for petroleum and natural gas extraction'),
(54, 8, 'Support activities for other mining and quarrying'),
(55, 9, 'Repair of fabricated metal products'),
(56, 9, 'Repair of machinery'),
(57, 9, 'Repair of electronic and optical equipment'),
(58, 9, 'Repair of electrical equipment'),
(59, 9, 'Repair of transport equipment, except motor vehicles'),
(60, 9, 'Repair of other equipment'),
(61, 9, 'Installation of industrial machinery and equipment'),
(62, 10, 'Manufacture of motor vehicles'),
(63, 10, 'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers'),
(64, 10, 'Manufacture of parts and accessories for motor vehicles'),
(65, 11, 'Building of ships and floating structures'),
(66, 11, 'Building of pleasure and sporting boats'),
(67, 11, 'Manufacture of railway locomotives and rolling stock'),
(68, 11, 'Manufacture of air and spacecraft and related machinery'),
(69, 11, 'Manufacture of military fighting vehicles'),
(70, 11, 'Manufacture of motorcycles'),
(71, 11, 'Manufacture of bicycles and invalid carriages'),
(72, 11, 'Manufacture of other transport equipment n.e.c.'),
(73, 12, 'Manufacture of furniture'),
(74, 13, 'Manufacture of imitation jewellery and related articles'),
(75, 13, 'Manufacture of musical instruments'),
(76, 13, 'Manufacture of sports goods'),
(77, 13, 'Manufacture of games and toys'),
(78, 13, 'Manufacture of medical and dental instruments and supplies'),
(79, 13, 'Other manufacturing n.e.c.'),
(80, 14, 'Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus'),
(81, 14, 'Manufacture of batteries and accumulators'),
(82, 14, 'Manufacture of fibre optic cables'),
(83, 14, 'Manufacture of other electronic and electric wires and cables'),
(84, 14, 'Manufacture of wiring devices'),
(85, 14, 'Manufacture of electric lighting equipment'),
(86, 14, 'Manufacture of domestic appliances'),
(87, 14, 'Manufacture of other electrical equipment'),
(88, 15, 'Manufacture of engines and turbines, except aircraft, vehicle and cycle engines'),
(89, 15, 'Manufacture of fluid power equipment'),
(90, 15, 'Manufacture of other pumps, compressors, taps and valves'),
(91, 15, 'Manufacture of bearings, gears, gearing and driving elements'),
(92, 15, 'Manufacture of ovens, furnaces and furnace burners'),
(93, 15, 'Manufacture of lifting and handling equipment'),
(94, 15, 'Manufacture of office machinery and equipment (except computers and peripheral equipment)'),
(95, 15, 'Manufacture of power-driven hand tools'),
(96, 15, 'Manufacture of other general-purpose machinery'),
(97, 15, 'Manufacture of agricultural and forestry machinery'),
(98, 15, 'Manufacture of metal-forming machinery and machine tools'),
(99, 15, 'Manufacture of machinery for metallurgy'),
(100, 15, 'Manufacture of machinery for mining, quarrying and construction'),
(101, 15, 'Manufacture of machinery for food, beverage and tobacco processing'),
(102, 15, 'Manufacture of machinery for textile, apparel and leather production'),
(103, 15, 'Manufacture of other special-purpose machinery'),
(104, 16, 'Manufacture of structural metal products'),
(105, 16, 'Manufacture of tanks, reservoirs and containers of metal'),
(106, 16, 'Manufacture of steam generators, except central heating hot water boilers'),
(107, 16, 'Manufacture of weapons and ammunition'),
(108, 16, 'Forging, pressing, stamping and roll-forming of metal; powder metallurgy'),
(109, 16, 'Treatment and coating of metals; machining'),
(110, 16, 'Manufacture of cutlery, hand tools and general hardware'),
(111, 16, 'Manufacture of other fabricated metal products n.e.c.'),
(112, 17, 'Manufacture of electronic components and boards'),
(113, 17, 'Manufacture of computers and peripheral equipment'),
(114, 17, 'Manufacture of communication equipment'),
(115, 17, 'Manufacture of consumer electronics'),
(116, 17, 'Manufacture of measuring, testing, navigating and control equipment'),
(117, 17, 'Manufacture of watches and clocks'),
(118, 17, 'Manufacture of irradiation, electromedical and electrotherapeutic equipment'),
(119, 17, 'Manufacture of optical instruments and photographic equipment'),
(120, 17, 'Manufacture of magnetic and optical media'),
(121, 18, 'Manufacture of pharmaceuticals, medicinal chemical and botanical products'),
(122, 19, 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres'),
(123, 19, 'Manufacture of other rubber products'),
(124, 19, 'Manufacture of plastics products'),
(125, 20, 'Manufacture of glass and glass products'),
(126, 20, 'Manufacture of refractory products'),
(127, 20, 'Manufacture of clay building materials'),
(128, 20, 'Manufacture of other porcelain and ceramic products'),
(129, 20, 'Manufacture of cement, lime and plaster'),
(130, 20, 'Manufacture of articles of concrete, cement and plaster'),
(131, 20, 'Cutting, shaping and finishing of stone'),
(132, 20, 'Manufacture of other non-metallic mineral products n.e.c.'),
(133, 21, 'Manufacture of basic iron and steel'),
(134, 21, 'Manufacture of basic precious and other non-ferrous metals'),
(135, 21, 'Casting of iron and steel'),
(136, 21, 'Casting of non-ferrous metals'),
(137, 22, 'Sawmilling and planing of wood'),
(138, 22, 'Manufacture of veneer sheets and wood-based panels'),
(139, 22, 'Manufacture of builders\' carpentry and joinery'),
(140, 22, 'Manufacture of wooden containers'),
(141, 22, 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials'),
(142, 23, 'Manufacture of pulp, paper and paperboard'),
(143, 23, 'Manufacture of corrugated paper and paperboard and of containers of paper and paperboard'),
(144, 23, 'Manufacture of other articles of paper and paperboard'),
(145, 24, 'Printing'),
(146, 24, 'Service activities related to printing'),
(147, 24, 'Reproduction of recorded media'),
(148, 25, 'Manufacture of coke oven products'),
(149, 25, 'Manufacture of refined petroleum products'),
(150, 26, 'Manufacture of basic chemicals'),
(151, 26, 'Manufacture of fertilizers and nitrogen compounds'),
(152, 26, 'Manufacture of plastics and synthetic rubber in primary forms'),
(153, 26, 'Manufacture of pesticides and other agrochemical products'),
(154, 26, 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
(155, 26, 'Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations'),
(156, 26, 'Manufacture of other chemical products n.e.c.'),
(157, 26, 'Manufacture of man-made fibres'),
(158, 27, 'Distilling, rectifying and blending of spirits'),
(159, 27, 'Manufacture of wines'),
(160, 27, 'Manufacture of malt liquors and malt'),
(161, 27, 'Manufacture of soft drinks; production of mineral waters and other bottled waters'),
(162, 28, 'Manufacture of tobacco products'),
(163, 29, 'Preparation and spinning of textile fibres'),
(164, 29, 'Weaving of textiles'),
(165, 29, 'Finishing of textiles'),
(166, 30, 'Manufacture of wearing apparel, except fur apparel'),
(167, 30, 'Manufacture of articles of fur'),
(168, 30, 'Manufacture of knitted and crocheted apparel'),
(169, 31, 'Tanning and dressing of leather; dressing and dyeing of fur'),
(170, 31, 'Manufacture of luggage, handbags and the like, saddlery and harness'),
(171, 31, 'Manufacture of footwear'),
(172, 32, 'Processing and preserving of meat'),
(173, 32, 'Processing and preserving of fish, crustaceans and molluscs'),
(174, 32, 'Processing and preserving of fruit and vegetables'),
(175, 32, 'Manufacture of vegetable and animal oils and fats'),
(176, 32, 'Manufacture of dairy products'),
(177, 32, 'Manufacture of grain mill products'),
(178, 32, 'Manufacture of starches and starch products'),
(179, 32, 'Manufacture of bakery products'),
(180, 32, 'Manufacture of sugar'),
(181, 32, 'Manufacture of cocoa, chocolate and sugar confectionery'),
(182, 32, 'Manufacture of macaroni, noodles, couscous and similar farinaceous products'),
(183, 32, 'Manufacture of prepared meals and dishes'),
(184, 32, 'Manufacture of other food products n.e.c.'),
(185, 32, 'Manufacture of prepared animal feeds'),
(186, 33, 'Electric power generation, transmission and distribution'),
(187, 33, 'Manufacture of gas; distribution of gaseous fuels through mains'),
(188, 33, 'Steam and air conditioning supply'),
(189, 34, 'Remediation activities and other waste management services'),
(190, 87, 'Water collection, treatment and supply'),
(191, 35, 'Sewerage'),
(192, 36, 'Collection of non-hazardous waste'),
(193, 36, 'Collection of hazardous waste'),
(194, 36, 'Treatment and disposal of non-hazardous waste'),
(195, 36, 'Treatment and disposal of hazardous waste'),
(196, 36, 'Materials recovery'),
(197, 37, 'Construction of buildings'),
(198, 38, 'Construction of roads and railways'),
(199, 38, 'Construction of utility projects'),
(200, 38, 'Construction of other civil engineering projects'),
(201, 39, 'Demolition'),
(202, 39, 'Site preparation'),
(203, 39, 'Electrical installation'),
(204, 39, 'Plumbing, heat and air-conditioning installation'),
(205, 39, 'Other construction installation'),
(206, 39, 'Building completion and finishing'),
(207, 39, 'Other specialized construction activities'),
(208, 40, 'Wholesale on a fee or contract basis'),
(209, 40, 'Wholesale of agricultural raw materials and live animals'),
(210, 40, 'Wholesale of food, beverages and tobacco'),
(211, 40, 'Wholesale of textiles, clothing and footwear'),
(212, 40, 'Wholesale of other household goods'),
(213, 40, 'Wholesale of computers, computer peripheral equipment and software'),
(214, 40, 'Wholesale of electronic and telecommunications equipment and parts'),
(215, 40, 'Wholesale of agricultural machinery, equipment and supplies'),
(216, 40, 'Wholesale of other machinery and equipment'),
(217, 40, 'Wholesale of solid, liquid and gaseous fuels and related products'),
(218, 40, 'Wholesale of metals and metal ores'),
(219, 40, 'Wholesale of construction materials, hardware, plumbing and heating equipment and supplies'),
(220, 40, 'Wholesale of waste and scrap and other products n.e.c.'),
(221, 40, 'Non-specialized wholesale trade'),
(222, 41, 'Retail sale in non-specialized stores with food, beverages or tobacco predominating'),
(223, 41, 'Other retail sale in non-specialized stores'),
(224, 41, 'Retail sale of food in specialized stores'),
(225, 41, 'Retail sale of beverages in specialized stores'),
(226, 41, 'Retail sale of tobacco products in specialized stores'),
(227, 41, 'Retail sale of automotive fuel in specialized stores'),
(228, 41, 'Retail sale of computers, peripheral units, software and telecommunications equipment in specialized stores'),
(229, 41, 'Retail sale of audio and video equipment in specialized stores'),
(230, 41, 'Retail sale of textiles in specialized stores'),
(231, 41, 'Retail sale of hardware, paints and glass in specialized stores'),
(232, 41, 'Retail sale of carpets, rugs, wall and floor coverings in specialized stores'),
(233, 41, 'Retail sale of electrical household appliances, furniture, lighting equipment and other household articles in specialized stores'),
(234, 41, 'Retail sale of books, newspapers and stationary in specialized stores'),
(235, 41, 'Retail sale of music and video recordings in specialized stores'),
(236, 41, 'Retail sale of sporting equipment in specialized stores'),
(237, 41, 'Retail sale of games and toys in specialized stores'),
(238, 41, 'Retail sale of clothing, footwear and leather articles in specialized stores'),
(239, 41, 'Retail sale of pharmaceutical and medical goods, cosmetic and toilet articles in specialized stores'),
(240, 41, 'Other retail sale of new goods in specialized stores'),
(241, 41, 'Retail sale of second-hand goods'),
(242, 41, 'Retail sale via stalls and markets of food, beverages and tobacco products'),
(243, 41, 'Retail sale via stalls and markets of textiles, clothing and footwear'),
(244, 41, 'Retail sale via stalls and markets of other goods'),
(245, 41, 'Retail sale via mail order houses or via Internet'),
(246, 41, 'Other retail sale not in stores, stalls or markets'),
(247, 42, 'Sale of motor vehicles'),
(248, 42, 'Maintenance and repair of motor vehicles'),
(249, 42, 'Sale of motor vehicle parts and accessories'),
(250, 42, 'Sale, maintenance and repair of motorcycles and related parts and accessories'),
(251, 43, 'Passenger rail transport, interurban'),
(252, 43, 'Freight rail transport'),
(253, 43, 'Urban and suburban passenger land transport'),
(254, 43, 'Other passenger land transport'),
(255, 43, 'Freight transport by road'),
(256, 43, 'Transport via pipeline'),
(257, 44, 'Sea and coastal passenger water transport'),
(258, 44, 'Sea and coastal freight water transport'),
(259, 44, 'Inland passenger water transport'),
(260, 44, 'Inland freight water transport'),
(261, 45, 'Passenger air transport'),
(262, 45, 'Freight air transport'),
(263, 46, 'Warehousing and storage'),
(264, 46, 'Service activities incidental to land transportation'),
(265, 46, 'Service activities incidental to water transportation'),
(266, 46, 'Service activities incidental to air transportation'),
(267, 46, 'Cargo handling'),
(268, 46, 'Other transportation support activities'),
(269, 47, 'Postal activities'),
(270, 47, 'Courier activities'),
(271, 48, 'Short term accommodation activities'),
(272, 48, 'Camping grounds, recreational vehicle parks and trailer parks'),
(273, 48, 'Other accommodation'),
(274, 49, 'Restaurants and mobile food service activities'),
(275, 49, 'Event catering'),
(276, 49, 'Other food service activities'),
(277, 49, 'Beverage serving activities'),
(278, 50, 'Motion picture, video and television programme production activities'),
(279, 50, 'Motion picture, video and television programme post-production activities'),
(280, 50, 'Motion picture, video and television programme distribution activities'),
(281, 50, 'Motion picture projection activities'),
(282, 50, 'Sound recording and music publishing activities'),
(283, 51, 'Radio broadcasting'),
(284, 52, 'Wired telecommunications activities'),
(285, 52, 'Wireless telecommunications activities'),
(286, 52, 'Satellite telecommunications activities'),
(287, 52, 'Other telecommunications activities'),
(288, 53, 'Computer programming activities'),
(289, 53, 'Computer consultancy and computer facilities management activities'),
(290, 53, 'Other information technology and computer service activities'),
(291, 54, 'Data processing, hosting and related activities'),
(292, 54, 'Web portals'),
(293, 55, 'Book publishing'),
(294, 55, 'Publishing of directories and mailing lists'),
(295, 55, 'Publishing of newspapers, journals and periodicals'),
(296, 55, 'Other publishing activities'),
(297, 55, 'Software publishing'),
(298, 56, 'Central banking'),
(299, 56, 'Other monetary intermediation'),
(300, 56, 'Activities of holding companies'),
(301, 56, 'Trusts, funds and similar financial entities'),
(302, 56, 'Financial leasing'),
(303, 56, 'Other credit granting'),
(304, 56, 'Other financial service activities, except insurance and pension funding activities, n.e.c.'),
(305, 57, 'Life insurance'),
(306, 57, 'Non-life insurance'),
(307, 57, 'Reinsurance'),
(308, 57, 'Pension funding'),
(309, 58, 'Administration of financial markets'),
(310, 58, 'Security and commodity contracts brokerage'),
(311, 58, 'Other activities auxiliary to financial service activities'),
(312, 58, 'Risk and damage evaluation'),
(313, 58, 'Activities of insurance agents and brokers'),
(314, 58, 'Other activities auxiliary to insurance and pension funding'),
(315, 58, 'Fund management activities'),
(316, 59, 'Real estate activities with own or leased property'),
(317, 59, 'Real estate activities on a fee or contract basis'),
(318, 60, 'Legal activities'),
(319, 60, 'Accounting, bookkeeping and auditing activities; tax consultancy'),
(320, 61, 'Activities of head offices'),
(321, 61, 'Management consultancy activities'),
(322, 62, 'Architectural and engineering activities and related technical consultancy'),
(323, 62, 'Technical testing and analysis'),
(324, 63, 'Research and experimental development on natural sciences and engineering'),
(325, 63, 'Research and experimental development on social sciences and humanities'),
(326, 64, 'Advertising'),
(327, 64, 'Market research and public opinion polling'),
(328, 65, 'Specialized design activities'),
(329, 65, 'Photographic activities'),
(330, 65, 'Other professional, scientific and technical activities n.e.c.'),
(331, 66, 'Veterinary activities'),
(332, 67, 'Activities of employment placement agencies'),
(333, 67, 'Temporary employment agency activities'),
(334, 67, 'Other human resources provision'),
(335, 68, 'Travel agency activities'),
(336, 68, 'Tour operator activities'),
(337, 69, 'Private security activities'),
(338, 69, 'Security systems service activities'),
(339, 69, 'Investigation activities'),
(340, 70, 'Combined facilities support activities'),
(341, 70, 'General cleaning of buildings'),
(342, 70, 'Other building and industrial cleaning activities'),
(343, 70, 'Landscape care and maintenance service activities'),
(344, 71, 'Combined office administrative service activities'),
(345, 71, 'Photocopying, document preparation and other specialized office support activities'),
(346, 71, 'Activities of call centres'),
(347, 71, 'Organization of conventions and trade shows'),
(348, 71, 'Activities of collection agencies and credit bureaus'),
(349, 71, 'Packaging activities'),
(350, 71, 'Other business support service activities n.e.c.'),
(351, 71, 'Renting and leasing of motor vehicles'),
(352, 71, 'Renting and leasing of recreational and sports goods'),
(353, 71, 'Renting of video tapes and disks'),
(354, 71, 'Renting and leasing of other personal and household goods'),
(355, 71, 'Renting and leasing of other machinery, equipment and tangible goods'),
(356, 71, 'Leasing of intellectual property and similar products, except copyrighted works'),
(357, 72, 'General public administration activities'),
(358, 72, 'Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security'),
(359, 72, 'Regulation of and contribution to more efficient operation of businesses'),
(360, 72, 'Foreign affairs'),
(361, 72, 'Defence activities'),
(362, 72, 'Public order and safety activities'),
(363, 72, 'Compulsory social security activities'),
(364, 73, 'Pre-primary and primary education'),
(365, 73, 'General secondary education'),
(366, 73, 'Technical and vocational secondary education'),
(367, 73, 'Higher education'),
(368, 73, 'Sports and recreation education'),
(369, 73, 'Cultural education'),
(370, 73, 'Other education n.e.c.'),
(371, 73, 'Educational support activities'),
(372, 74, 'Hospital activities'),
(373, 74, 'Medical and dental practice activities'),
(374, 74, 'Other human health activities'),
(375, 75, 'Residential nursing care facilities'),
(376, 75, 'Residential care activities for mental retardation, mental health and substance abuse'),
(377, 75, 'Residential care activities for the elderly and disabled'),
(378, 75, 'Other residential care activities'),
(379, 76, 'Social work activities without accommodation for the elderly and disabled'),
(380, 76, 'Other social work activities without accommodation'),
(381, 77, 'Library and archives activities'),
(382, 77, 'Museums activities and operation of historical sites and buildings'),
(383, 77, 'Botanical and zoological gardens and nature reserves activities'),
(384, 78, 'Gambling and betting activities'),
(385, 79, 'Operation of sports facilities'),
(386, 79, 'Activities of sports clubs'),
(387, 79, 'Other sports activities'),
(388, 79, 'Activities of amusement parks and theme parks'),
(389, 79, 'Other amusement and recreation activities n.e.c.'),
(390, 80, 'Creative, arts and entertainment activities'),
(391, 81, 'Activities of business and employers membership organizations'),
(392, 81, 'Activities of professional membership organizations'),
(393, 81, 'Activities of trade unions'),
(394, 81, 'Activities of religious organizations'),
(395, 81, 'Activities of political organizations'),
(396, 81, 'Activities of other membership organizations n.e.c.'),
(397, 82, 'Repair of computers and peripheral equipment'),
(398, 82, 'Repair of communication equipment'),
(399, 82, 'Repair of consumer electronics'),
(400, 82, 'Repair of household appliances and home and garden equipment'),
(401, 82, 'Repair of footwear and leather goods'),
(402, 82, 'Repair of furniture and home furnishings'),
(403, 82, 'Repair of other personal and household goods'),
(404, 83, 'Washing and (dry-) cleaning of textile and fur products'),
(405, 83, 'Hairdressing and other beauty treatment'),
(406, 83, 'Funeral and related activities'),
(407, 83, 'Other personal service activities n.e.c.'),
(408, 84, 'Activities of households as employers of domestic personnel'),
(409, 85, 'Undifferentiated goods-producing activities of private households for own use'),
(410, 85, 'Undifferentiated service-producing activities of private households for own use'),
(411, 86, 'Activities of extraterritorial organizations and bodies'),
(523, 89, 'Agriculture');
