-- Zone import from docs/zone.xlsx
-- Generated: This updates districts with zone values

UPDATE districts SET zone = NULL;

-- Zone 1 (SEZ)
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'may';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'samphanh';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'yot ou';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'nga';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'phonxay';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'pak seng';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'viengkham';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'phonthong';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'samtay';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'nong het';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'mok may';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'phonhong';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'thoulakhom';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'keo oudom';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'kasy';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'vangvieng';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'feuang';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'xanakharm';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'mad';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'viengkham';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'hinhurp';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'nong';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'kaleum';
UPDATE districts SET zone = 1 WHERE LOWER(district_name) = 'thathom';

-- Zone 2 (Promotion)
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'chanthabuly';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sikhottabong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'xaysetha';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sisattanak';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'naxaithong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'xaythany';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'hadxayfong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sangthong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'mayparkngum';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phongsaly';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'khoua';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'boun neua';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'boun tay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'namtha';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sing';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'long';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'viengphoukha';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'na le';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'xay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'la';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'na mo';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'beng';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pak beng';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'houayxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'ton pheung';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'meung';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pha oudom';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pak tha';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pak ou';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'ngoy';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'chomphet';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phoukhoune';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'xam neua';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'viengxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sop bao';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'et';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'kone';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sainyabuli';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'khop';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'hongsa';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'ngeun';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phiang';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'parklai';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'kenethao';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'botene';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'thongmyxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pek';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'kham';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'khoune';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phou kout';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phaxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'pakkading';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'borikhane';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'khamkeut';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'viengthong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'thakhek';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'mahaxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'nong bok';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'hineboune';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'nakai';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'kounkham';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'outhoumphone';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'atsaphangthong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phine';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'thapangthong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'songkhone';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'champhone';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'assaphone';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'xonboury';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'thaphalanxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'toumlane';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'lakhonepheng';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'lao ngam';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'kaleum';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sanasomboun';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'paksong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phonthong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'mounlapamok';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'khong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'samakkhixay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'sanamxay';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'phouvong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'anouvong';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'longchaeng';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'longxan';
UPDATE districts SET zone = 2 WHERE LOWER(district_name) = 'hom';
